services:
  - type: web
    name: campus-eye-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
