// Comprehensive training dataset of college & campus complaints across 8 major domains
module.exports = [
  // --- EMERGENCY & SAFETY (18 samples) ---
  { text: "Fire detected in the chemistry lab on 2nd floor, smoke coming out", category: "Emergency", priority: "Critical" },
  { text: "Electric spark and burning smell from switchboard near staircase", category: "Emergency", priority: "Critical" },
  { text: "Gas cylinder leaking smell near hostel mess kitchen", category: "Emergency", priority: "Critical" },
  { text: "Ceiling plaster fell down and cracked, dangerous for students sitting below", category: "Emergency", priority: "Critical" },
  { text: "Live wire hanging loose from the corridor ceiling, risk of severe shock", category: "Emergency", priority: "Critical" },
  { text: "Student fainted and bleeding from head injury in sports ground", category: "Emergency", priority: "Critical" },
  { text: "Short circuit burst in server room with flames", category: "Emergency", priority: "Critical" },
  { text: "Glass window shattered by wind and sharp shards falling into walkway", category: "Emergency", priority: "Critical" },
  { text: "Chemical spill of acid in the organic chemistry laboratory", category: "Emergency", priority: "Critical" },
  { text: "Elevator lift stuck between 3rd and 4th floor with 5 students inside", category: "Emergency", priority: "Critical" },
  { text: "Fire alarm ringing and thick black smoke near basement parking", category: "Emergency", priority: "Critical" },
  { text: "Snake spotted inside ground floor seminar hall near stage", category: "Emergency", priority: "Critical" },
  { text: "Balcony railing loose and shaking, could collapse anytime", category: "Emergency", priority: "Critical" },
  { text: "Severe water flooding inside main electrical switchgear panel", category: "Emergency", priority: "Critical" },
  { text: "Burning wire odor in computer lab 3, students evacuated", category: "Emergency", priority: "Critical" },
  { text: "Staircase steps broken, two students tripped and hurt badly", category: "Emergency", priority: "High" },
  { text: "Main water storage tank overflowing violently causing structural flood", category: "Emergency", priority: "High" },
  { text: "Emergency exit door is locked and blocked by junk furniture", category: "Emergency", priority: "High" },

  // --- ELECTRICAL & POWER (22 samples) ---
  { text: "Ceiling fan making loud grinding noise and wobbling dangerously in room 201", category: "Electrical", priority: "High" },
  { text: "Power socket is dead, cannot plug in laptop or projector in class 4B", category: "Electrical", priority: "Medium" },
  { text: "Tube lights are flickering continuously causing severe headache in seminar room", category: "Electrical", priority: "Medium" },
  { text: "Air conditioner in computer lab 2 is blowing hot air and not cooling", category: "Electrical", priority: "High" },
  { text: "Frequent power cuts and tripping MCB breaker in block A every 10 minutes", category: "Electrical", priority: "High" },
  { text: "Switch board switch is broken and internal contacts are exposed", category: "Electrical", priority: "High" },
  { text: "Geyser in hostel bathroom floor 3 is not heating water at all", category: "Electrical", priority: "Medium" },
  { text: "Street lights outside library pathway are off at night, very dark and unsafe", category: "Electrical", priority: "High" },
  { text: "Extension power strip in seminar hall gave mild electrical shock when touched", category: "Electrical", priority: "High" },
  { text: "Projector power cord disconnected inside ceiling mount", category: "Electrical", priority: "Medium" },
  { text: "Cooling exhaust fans in physics lab have stopped working, room heating up", category: "Electrical", priority: "Medium" },
  { text: "All lights in the reading room are completely fused and out", category: "Electrical", priority: "High" },
  { text: "Digital clock and PA system speaker not receiving power", category: "Electrical", priority: "Low" },
  { text: "Inverter backup failed during yesterday power outage, computers turned off", category: "Electrical", priority: "High" },
  { text: "Sparking noise heard behind the wall outlet in room 305", category: "Electrical", priority: "High" },
  { text: "AC remote controller missing and temperature stuck at 16 degrees", category: "Electrical", priority: "Low" },
  { text: "Corridor emergency lights are discharged and dead", category: "Electrical", priority: "Medium" },
  { text: "Computer power supply unit burned out with bad smell", category: "Electrical", priority: "High" },
  { text: "Fan regulator knob cracked and speed cannot be lowered", category: "Electrical", priority: "Low" },
  { text: "Main distribution board fuse blown in mechanical department", category: "Electrical", priority: "High" },
  { text: "Microwave in student cafeteria pantry does not turn on", category: "Electrical", priority: "Low" },
  { text: "Water cooler compressor is not turning on, water is boiling hot", category: "Electrical", priority: "Medium" },

  // --- NETWORK & WIFI (22 samples) ---
  { text: "WiFi internet in Block C hostel is completely down since yesterday", category: "Network", priority: "High" },
  { text: "Campus WiFi speed is extremely slow, under 100 kbps, unable to submit assignment", category: "Network", priority: "High" },
  { text: "Captive portal login page fails to load or authenticate student credentials", category: "Network", priority: "Medium" },
  { text: "LAN ethernet port on desk 14 in computer lab 1 has no signal", category: "Network", priority: "Medium" },
  { text: "WiFi router in corridor 2nd floor keeps rebooting and disconnecting devices", category: "Network", priority: "Medium" },
  { text: "Eduroam network not connecting on iOS and Mac devices", category: "Network", priority: "Medium" },
  { text: "High ping latency and heavy packet loss during online placement test", category: "Network", priority: "High" },
  { text: "Library digital catalog cannot connect to campus intranet server", category: "Network", priority: "Medium" },
  { text: "Ethernet cable clip broken and connector falls out of socket", category: "Network", priority: "Low" },
  { text: "DNS server error cannot resolve external educational websites", category: "Network", priority: "Medium" },
  { text: "Access point red light blinking, no internet connectivity for entire floor", category: "Network", priority: "High" },
  { text: "Hostel WiFi signal is too weak inside corner rooms 101 to 106", category: "Network", priority: "Low" },
  { text: "College portal student dashboard throwing 504 gateway timeout", category: "Network", priority: "High" },
  { text: "Firewall blocking access to GitHub and academic research papers", category: "Network", priority: "Medium" },
  { text: "WiFi password expired and SMS OTP verification not coming", category: "Network", priority: "Medium" },
  { text: "Server rack network switch port led flashing amber, network loop suspected", category: "Network", priority: "High" },
  { text: "Bandwidth throttling making research journal downloads fail", category: "Network", priority: "Medium" },
  { text: "Hostel block D has had zero internet connection for the last 3 days", category: "Network", priority: "High" },
  { text: "Printer on network cannot be discovered from lab terminals", category: "Network", priority: "Medium" },
  { text: "VPN access for remote library databases is rejected", category: "Network", priority: "Medium" },
  { text: "Frequent WiFi disconnections every five minutes while working on project", category: "Network", priority: "High" },
  { text: "Ethernet wall jack faceplate pulled out with bare cables showing", category: "Network", priority: "Medium" },

  // --- PLUMBING & WATER (20 samples) ---
  { text: "Water pipe burst under the washbasin, corridor flooded with water", category: "Plumbing", priority: "High" },
  { text: "Tap continuously dripping water and wasting water in 1st floor bathroom", category: "Plumbing", priority: "Medium" },
  { text: "Toilet flush tank lever broken, bowl won't flush", category: "Plumbing", priority: "High" },
  { text: "No water in boys hostel block B since early morning, taps are dry", category: "Plumbing", priority: "High" },
  { text: "Sink drain is clogged with hair and stagnant dirty water accumulating", category: "Plumbing", priority: "Medium" },
  { text: "Drinking water cooler tap leaking puddle onto the floor, slip hazard", category: "Plumbing", priority: "Medium" },
  { text: "Water pressure on 4th floor washrooms is zero, trickling droplets only", category: "Plumbing", priority: "Medium" },
  { text: "Sewage water backing up from the floor drain with terrible stench", category: "Plumbing", priority: "High" },
  { text: "Drinking water dispenser coming out brown and muddy, unsafe to drink", category: "Plumbing", priority: "Critical" },
  { text: "Shower head missing in hostel bathroom cubicle 4", category: "Plumbing", priority: "Low" },
  { text: "Urinal sensor flush valve stuck running water continuously", category: "Plumbing", priority: "Medium" },
  { text: "Drainage pipe outside cafeteria leaking foul smelling grease water", category: "Plumbing", priority: "High" },
  { text: "Washroom tap handle broken off, impossible to turn water on", category: "Plumbing", priority: "Medium" },
  { text: "Water tank overflow pipe gushing water on pedestrians below", category: "Plumbing", priority: "Medium" },
  { text: "Hot water pipe leaking scalding water in the hostel corridor", category: "Plumbing", priority: "High" },
  { text: "Water filter cartridge past expiry, water tastes metallic and foul", category: "Plumbing", priority: "High" },
  { text: "Toilet commode seal broken, leaking water on floor around base", category: "Plumbing", priority: "High" },
  { text: "Bathroom door latch stuck from inside due to moisture swelling", category: "Plumbing", priority: "Medium" },
  { text: "Roof rainwater gutter clogged causing leakage through ceiling", category: "Plumbing", priority: "High" },
  { text: "Hand wash soap dispenser tap loose and falling off wall", category: "Plumbing", priority: "Low" },

  // --- ACADEMIC & CLASSROOM (18 samples) ---
  { text: "Classroom projector display is flickering green and cuts out during lecture", category: "Academic", priority: "High" },
  { text: "Podium microphone producing loud screeching feedback noise", category: "Academic", priority: "Medium" },
  { text: "Smart interactive board touch sensors not working, stylus unresponsive", category: "Academic", priority: "Medium" },
  { text: "Whiteboard is heavily stained, dry erase markers cannot be wiped off", category: "Academic", priority: "Low" },
  { text: "HDMI cable on instructor desk is bent and displays no audio video", category: "Academic", priority: "Medium" },
  { text: "Broken benches with sharp nails sticking out in lecture hall 3", category: "Academic", priority: "High" },
  { text: "Computer lab terminal 24 has dead keyboard with missing spacebar", category: "Academic", priority: "Low" },
  { text: "Digital oscilloscope in electronics lab is not calibrated, erroneous readings", category: "Academic", priority: "Medium" },
  { text: "Not enough chairs for registered students in section B seminar hall", category: "Academic", priority: "Medium" },
  { text: "Sound system amplifier in auditorium cuts audio every 2 minutes", category: "Academic", priority: "Medium" },
  { text: "Curtains torn and sunlight reflects on projector screen making notes illegible", category: "Academic", priority: "Low" },
  { text: "Laboratory chemical balance scale displaying error code Err-02", category: "Academic", priority: "Medium" },
  { text: "Professor cannot record online lecture because webcam mount is broken", category: "Academic", priority: "Medium" },
  { text: "Chalkboard cracked in two halves and unsteady on the wall mount", category: "Academic", priority: "Low" },
  { text: "Lab PC monitors have dead pixels and distorted colors", category: "Academic", priority: "Low" },
  { text: "Air ventilation poor in exam hall, suffocating environment during tests", category: "Academic", priority: "High" },
  { text: "Library book barcode scanner not scanning student IDs", category: "Academic", priority: "Low" },
  { text: "Software IDE license expired on all computer science lab machines", category: "Academic", priority: "High" },

  // --- HOUSEKEEPING & HYGIENE (18 samples) ---
  { text: "Washrooms in block 2 are extremely dirty and uncleaned for three days", category: "Housekeeping", priority: "High" },
  { text: "Garbage bins overflowing with plastic food boxes and fruit flies buzzing", category: "Housekeeping", priority: "Medium" },
  { text: "Stray cats and cockroaches spotted inside the student dining hall", category: "Housekeeping", priority: "High" },
  { text: "Water spilled in main corridor makes floor extremely slippery", category: "Housekeeping", priority: "High" },
  { text: "Dust and cobwebs accumulating on classroom windows and ceiling fans", category: "Housekeeping", priority: "Low" },
  { text: "Foul odor coming from unemptied trash cans near lecture rooms", category: "Housekeeping", priority: "Medium" },
  { text: "Sanitary pads disposal bin full and not cleared in girls restroom", category: "Housekeeping", priority: "High" },
  { text: "Corridor floor covered in mud and shoe marks after heavy rains", category: "Housekeeping", priority: "Low" },
  { text: "Pigeon droppings on desks and window sills in classroom 102", category: "Housekeeping", priority: "Medium" },
  { text: "Washroom mirrors cracked and covered in grime", category: "Housekeeping", priority: "Low" },
  { text: "Hand sanitizer stations are completely empty in academic block", category: "Housekeeping", priority: "Low" },
  { text: "Stagnant puddle outside department entrance breeding mosquitoes", category: "Housekeeping", priority: "Medium" },
  { text: "Used tissue papers and wrappers scattered all over seminar hall stairs", category: "Housekeeping", priority: "Low" },
  { text: "Dirty tables and sticky residue left on cafeteria food counters", category: "Housekeeping", priority: "Medium" },
  { text: "Termite dust falling onto desks in old library archives", category: "Housekeeping", priority: "Medium" },
  { text: "Vending machine area littered with spilled soda and insect invasion", category: "Housekeeping", priority: "Medium" },
  { text: "Washroom soap dispensers empty, no liquid soap available", category: "Housekeeping", priority: "Low" },
  { text: "Classroom floor not swept, layers of dust on chairs", category: "Housekeeping", priority: "Low" },

  // --- HOSTEL & MESS (18 samples) ---
  { text: "Hostel mess food served today was undercooked and smelling sour", category: "Hostel", priority: "High" },
  { text: "Found dead caterpillar/insect inside rice served at dinner", category: "Hostel", priority: "Critical" },
  { text: "Common laundry washing machine error E4, drum locked with clothes inside", category: "Hostel", priority: "Medium" },
  { text: "Hostel room door lock is completely jammed, cannot lock or unlock room", category: "Hostel", priority: "High" },
  { text: "Bed bugs in room 204 mattress, students getting skin rashes", category: "Hostel", priority: "High" },
  { text: "Mess drinking water dispenser has bad chemical chlorine taste", category: "Hostel", priority: "High" },
  { text: "Hostel night study room air conditioning off and windows locked", category: "Hostel", priority: "Medium" },
  { text: "Stray dogs roaming inside hostel corridor barking at night", category: "Hostel", priority: "Medium" },
  { text: "Hostel warden room bell broken, cannot reach staff in emergency", category: "Hostel", priority: "Medium" },
  { text: "Mess food utensils and steel plates greasy and poorly washed", category: "Hostel", priority: "High" },
  { text: "Cloth drying racks on hostel terrace broken and rusted", category: "Hostel", priority: "Low" },
  { text: "Curfew biometric machine in hostel entrance misreading student thumbs", category: "Hostel", priority: "Medium" },
  { text: "Cold water in hostel geyser during peak winter morning", category: "Hostel", priority: "Medium" },
  { text: "Milk delivered in hostel mess is curdled and spoiled", category: "Hostel", priority: "High" },
  { text: "Ironing table in laundry room has broken leg, safety hazard", category: "Hostel", priority: "Low" },
  { text: "Loud party and music in neighboring hostel room past midnight", category: "Hostel", priority: "Medium" },
  { text: "Room wardrobe hinges loose, wooden door detached", category: "Hostel", priority: "Low" },
  { text: "Hostel water cooler has electric tingle when touching the steel body", category: "Hostel", priority: "Critical" },

  // --- INFRASTRUCTURE & SECURITY (16 samples) ---
  { text: "Biometric attendance scanner at main gate not registering student punch", category: "Security", priority: "Medium" },
  { text: "Parking lot gate barrier arm broken, cars blocking campus exit", category: "Security", priority: "Medium" },
  { text: "CCTV camera outside library is turned facing wall and blinking red", category: "Security", priority: "High" },
  { text: "Campus ID card turnstiles stuck in locked position creating huge queue", category: "Security", priority: "High" },
  { text: "Pothole in campus road near gate 2 causing bike riders to lose balance", category: "Infrastructure", priority: "High" },
  { text: "Main entrance gate wheel off track, difficult to push or secure", category: "Security", priority: "Medium" },
  { text: "Street light fixture hanging by wire in the parking lot", category: "Infrastructure", priority: "High" },
  { text: "Security guard absent from hostel gate late at night", category: "Security", priority: "High" },
  { text: "Footpath tiles broken creating walking hazard for elderly faculty", category: "Infrastructure", priority: "Medium" },
  { text: "Bicycle stands bent and overcrowded near athletic complex", category: "Infrastructure", priority: "Low" },
  { text: "Auditorium main glass entrance door has cracked pane", category: "Infrastructure", priority: "High" },
  { text: "Speed breaker on campus road has faded paint, invisible in dark", category: "Infrastructure", priority: "Medium" },
  { text: "College bus tyre punctured, replacement vehicle required immediately", category: "Infrastructure", priority: "High" },
  { text: "Security alarm false ringing continuously at administrative block", category: "Security", priority: "Low" },
  { text: "Wheelchair access ramp blocked by parked motorcycles", category: "Infrastructure", priority: "High" },
  { text: "Campus perimeter fence barbed wire cut open near sports ground", category: "Security", priority: "High" }
];
